services:

  postgres:
    image: postgres:14-alpine
    container_name: postgres-frame-house
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - back-end

  # Service with the spring back-end
  film-library:
    build:
      context: ./back-end/film-library-service 
      dockerfile: Dockerfile
    image: film-library-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - minio
      - postgres
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      AWS_S3_ENDPOINT_URL: http://minio:${MINIO_PORT}
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_S3_REGION: eu-east-1
    networks:
      - back-end


  # MinIO service for s3 object storage emulation
  minio:
    image: minio/minio:latest
    ports:
      # API port
      - "9000:${MINIO_PORT}"
      # Browser port
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - back-end
  


volumes:
  postgres-data:
  minio-data:
networks:
  back-end:
